package logic;
/* Generated By:JavaCC: Do not edit this line. AnalizadorLexicoConstants.java */
public interface AnalizadorLexicoConstants {

  int EOF = 0;
  int TERMINAL = 6;
  int PALABRARESERVADALEER = 7;
  int PALABRARESERVADASI = 8;
  int PALABRARESERVADAENTONCES = 9;
  int PALABRARESERVADASINO = 10;
  int PALABRARESERVADAFINSI = 11;
  int PALABRARESERVADAESCRIBIR = 12;
  int TIPODATOENTERO = 13;
  int TIPODATOCADENA = 14;
  int OPERADORCOMPARACIONMAYOR = 15;
  int OPERADORCOMPARACIONMENOR = 16;
  int CONCATENACION = 17;
  int COMENTARIO = 18;
  int ABRIRCORCHETE = 19;
  int CERRARCORCHETE = 20;
  int CADENAS = 21;
  int IDENTIFICADOR = 22;
  int ASIGNACION = 23;
  int OPERADORSUMA = 24;
  int OPERADORMULTIPLICACION = 25;
  int OPERADORDIVIDIDO = 26;
  int OPERADORMENOS = 27;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\".\"",
    "\"Leer\"",
    "\"Si\"",
    "\"Entonces\"",
    "\"Sino\"",
    "\"Finsi\"",
    "\"Escribir\"",
    "\"Numero\"",
    "\"Cadena\"",
    "\">\"",
    "\"<\"",
    "\"@\"",
    "<COMENTARIO>",
    "\"[\"",
    "\"]\"",
    "<CADENAS>",
    "<IDENTIFICADOR>",
    "\"=\"",
    "\"+\"",
    "\"*\"",
    "\"/\"",
    "\"-\"",
  };

}
